name: scope

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.12
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - numpy
  - transformers
  - protobuf
  - sentencepiece
  - wandb
  - tqdm
  - faiss-gpu
  - pyarrow
  - pylint
  - pytest
  - mypy
  - types-requests
  - pip
  - pip:
      - flash-attn
